version: '2'

services:
  database:
    image: postgres:9.4
    volumes:
      - ./public_html/database/:/home
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 

  web:
    ports:
      - "8056:80"
    build:
      context: ./Dockerfiles/php-apache
    volumes:
      - ./public_html/:/var/www/html/
    depends_on:
      - database
